dependency check placed--no-verify

diff --git a/.github/workflows/error-check.yml b/.github/workflows/error-check.yml
--- a/.github/workflows/error-check.yml
+++ b/.github/workflows/error-check.yml
@@ -25,15 +25,18 @@ jobs:
       - name: Run ESLint and Capture Output
         id: eslint_check
         run: |
-          ESLINT_OUTPUT=$(npx eslint clients/ --ext .js,.jsx,.ts,.tsx --format=json)
+          ESLINT_OUTPUT=$(npx eslint clients/ --ext .js,.jsx,.ts,.tsx --format=json || true)
           echo "$ESLINT_OUTPUT" > eslint_output.json
-          echo "ESLINT_FOUND_ERRORS=$(echo "$ESLINT_OUTPUT" | jq 'map(select(.errorCount > 0 or .warningCount > 0)) | length')" >> $GITHUB_ENV
+          ERROR_COUNT=$(echo "$ESLINT_OUTPUT" | jq '[.[] | .errorCount] | add')
+          WARNING_COUNT=$(echo "$ESLINT_OUTPUT" | jq '[.[] | .warningCount] | add')
+          echo "ESLINT_ERRORS=$ERROR_COUNT" >> $GITHUB_ENV
+          echo "ESLINT_WARNINGS=$WARNING_COUNT" >> $GITHUB_ENV
 
       - name: Debug ESLint Results
         run: cat eslint_output.json
 
       - name: Send Slack Notification on ESLint Errors or Warnings
-        if: env.ESLINT_FOUND_ERRORS != '0'
+        if: env.ESLINT_ERRORS != '0' || env.ESLINT_WARNINGS != '0'
         run: |
           curl -X POST -H 'Content-Type: application/json' --data '{
             "type": "event",
@@ -44,6 +47,8 @@ jobs:
                 "Branch": "${{ github.ref }}",
                 "Commit": "${{ github.sha }}",
                 "Actor": "${{ github.actor }}",
+                "Errors": "${{ env.ESLINT_ERRORS }}",
+                "Warnings": "${{ env.ESLINT_WARNINGS }}",
                 "Details": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Details>"
               }
             }
